### PR TITLE
Sentry Setup for Each Service

### PR DESCRIPTION
**Pull request by nh758**
Implements #55
- To get better Sentry data have each service initializes Sentry. This will help us capture uncaught errors, and provide better context for `notify()` errors.

## Release Notes

- add sentry integration
    - services can init sentry through ab-utils (with common default config options)
    - `nofity()` now sends to sentry directly rather than through `log_manager`
    - performance tracking in sentry for each service's handlers
 

Example of how services would use it: https://github.com/digi-serve/ab_service_log_manager/pull/34

### CODE REVIEW

**Review by joshAppDev — APPROVED** [review]
Can't say that I fully grasp all the details, but it looks good to me in principle.

One minor nitpick is that the new eslint-prettier seems to be adding `,` commas to the end of every list of function arguments whether they need it or not. It's valid JavaScript, but it seems weird. IMO, if developers type in that comma themselves, that's fine. But eslint shouldn't go out of its way to insert extra commas where none existed before.

**Comment by nh758** [comment]
It was a change in prettier, https://prettier.io/blog/2023/07/05/3.0.0.html#javascript
But easy to turn off if we want `{ "trailingComma": "es5" }`

**Review by Hiro-Nakamura — CHANGES_REQUESTED** [review]
OK, So I'm a little mixed about this update. 

In our original designs for this framework, we wanted to make it open source for others to possibly use this platform for their needs as well.  So along that line we wanted to provide some flexibility in some of our features.

In logging, I was expecting Sentry to be ONE of our options for logging.  I like Sentry and it is a great option.  But there are other logging strategies out there, aggregators and dashboards that we can feed our logs into that can be just as useful as Sentry.

It seems like this change and the changes to the `log_manager` are making Sentry THE logging option and not just ONE logging option.

Originally that is why all our `AB.notify.[developer,builder]()` calls funneled everything to the `log_manager` so we would have 1 location that would then channel our logs to the appropriate strategy.  

At the moment, we haven't implemented anything more than simply dumping the notification on the console and then performing manual searches on the linux console logs.

But we could implement other strategies.

So, do we want to allow the additional flexibility?  or are we saying we are just going all in on Sentry?  And will that be a requirement for others using our framework as well?

**Comment by nh758** [comment]
@Hiro-Nakamura 
The main reason for the change is to get better data for Sentry, and to use their Performance Tracking features. Which I'm hoping in the short term will help us figure out how to continue to improve performance.

I've refactored things so that Sentry is more optional. I've also switched to use open telemetry (which sentry works with), this should give us more flexibility to integrate with other tools in the future.

**Review by Hiro-Nakamura — APPROVED** [review]
OK, looks good.

**Pull request merged**
